### ISSUE TITLE
Can you include a sample of key usage in your documentation

### ISSUE THREAD

**Issue by sanderant** [remysaissy/ansible-ganglia#1]
I am new to Ansible. I am trying to get the gmond.conf to apply.

I modified the defaults/main.yml ds1 cluster just to see if that would work.

Then I tried to call out the variable directly using the following syntax
ganglia_config_gmond: 'ds1' but that is apparently the wrong syntax. Could you give an example in your readme?

Thank you for making this role!

**Comment by remysaissy** [comment]
Hi Sanderant,
from what I understand, your issue is related to the yaml syntax.
_ganglia_config_gmond: 'ds1' _ won't work because _ganglia_config_gmond_ is a yaml dictionary.
Therefore, the proper usage is 
_ganglia_config_gmond:_
(4 spaces)_'cluster name'_:
(8 spaces)...

**Comment by sanderant** [comment]
Thanks I am new to ansible and am still struggling with some of the yaml syntax.
