### ISSUE TITLE
Web front end picking up configuration from the wrong place in Amazon Linux

### ISSUE THREAD

**Issue by ldcasillas-progreso** [remysaissy/ansible-ganglia#10]
Somehow the web front end is picking up its configurations from the following file in Amazon Linux:

```
/usr/share/ganglia/conf.php
```

This file has no settings in it, so the effect is that there is no default view shown in the UI (none of the summary graphs appear at the top of the pages).  Editing that file and restarting httpd gets around the issues.

Note that there is a good default configuration file at this location, but it's not being read:

```
/etc/ganglia/conf.php
```

So the fix would be to modify the role so that the configuration is loaded from there.  I haven't yet figured out how to do it, but hopefully I will.

**Comment by remysaissy** [comment]
Ok,
this could be included as one of the vars.

To detect the Amazon flavor of RedHat, we can do this:
when: "ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'"

(from ansible-ganglia/tasks/repositories.yml)

Or we can also consider that this is something that should not be handled in the roles but rather by having a conf variable in defaults.

Both are ok for me.

**Comment by ldcasillas-progreso** [comment]
Oh, it turns out I filed this issue by mistake.  One file is a symlink to the other:

```
$ ls -l /usr/share/ganglia/conf.php /etc/ganglia/conf.php
-rw-r--r-- 1 root root 171 Mar 13  2015 /etc/ganglia/conf.php
lrwxrwxrwx 1 root root  29 Oct 12 20:47 /usr/share/ganglia/conf.php -> ../../../etc/ganglia/conf.php
```

Closing this.
