### ISSUE TITLE
ganglia_config_gmetad.setuid_username is not an "optional" property

### ISSUE THREAD

**Issue by ldcasillas-progreso** [remysaissy/ansible-ganglia#4]
Some comments in the `defaults/main.yml` file are prone to being misunderstood.  In particular, this one in the map for `ganglia_config_gmetad`:

```
# Optional parameters. Values below are gmeta's default values.
```

That makes it sound like you don't need to copy those map entries into your group variables files.  But in fact you do need to do so, or you get errors like this one:

```
TASK: [ganglia | Ensure the gmetad user exists] ******************************* 
fatal: [xxx.xxx.xxx.xxx] => One or more undefined variables: 'dict object' has no attribute 'setuid_username'
```

**Comment by remysaissy** [comment]
Indeed, that's because of the hash_behaviour  = merge ([defaults] section of ansible.cfg) that I use in order to work with the map so we don't need to copy the whole map.

I will add a comment to explain it in the README.md.

**Comment by ldcasillas-progreso** [comment]
Makes sense.  I would suggest mentioning this in the relevant comments as well.

**Comment by remysaissy** [comment]
Good idea.
