### ISSUE TITLE
Get rid of a permission denied when accessing the Ganglia UI (/ganglia) after the webfrontend deployment

### ISSUE THREAD

**Issue by remysaissy** [remysaissy/ansible-ganglia#7]
After the installation of httpd/apache2 and the ganglia conf template, there is a permission denied when accessing to the /ganglia URL even though permissions on the /usr/share/ganglia path are rx for others.

[Wed Oct 07 06:48:38.751497 2015] [authz_core:error] [pid 5610] [client 88.165.13.185:51051] AH01630: client denied by server configuration: /usr/share/ganglia

**Comment by ldcasillas-progreso** [comment]
I was going to report this as well but you got there ahead of me.  Yes, `Require all granted` fixes that in my environment.
